### ISSUE TITLE
[Epic] Growthbook Notes API 

### ISSUE THREAD

**Issue by andrewphm** [andrewphm/growthbook#1]
```[tasklist]
### Tasks
- [x] Flex comp landing page design
- [x] Flex comp landing page finalized copy
- [x] Flex comp landing page build
- [ ] Add disclaimer to US job postings
```
